### PR TITLE
extents - fix extents not starting with a number

### PR DESCRIPTION
**Pull request by walkerdb**
all in 3 finding aids. Generally the problematic extents were either moved to `<odd>` tags or made into physfacets

### CODE REVIEW

**Comment by eckardm** [comment]
Nice! Does this take care of extents that don't start with a number?

**Comment by walkerdb** [comment]
This should be the last of them, yeah.

**Comment by eckardm** [comment]
So this means that all extents can be imported without errors?

On Wed, Sep 16, 2015 at 3:53 PM, Walker Boyle notifications@github.com
wrote:

> This should be the last of them, yeah.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/bentley-historical-library/vandura/pull/218#issuecomment-140868309
> .

## 

_Max Eckard_
_Assistant Archivist for Digital Curation_

Bentley Historical Library
1150 Beal Ave.
Ann Arbor, MI 48109-2113
734/763-7518 <734.763.7518>
http://bentley.umich.edu/

**Comment by djpillen** [comment]
I just checked and there are still a handful of extents that begin with letters -- mostly collection level extents of the form "ca. etc. etc." 

But there aren't many.

**Comment by eckardm** [comment]
Walker, can you take care of those?

On Wed, Sep 16, 2015 at 3:56 PM, djpillen notifications@github.com wrote:

> I just checked and there are still a handful of extents that begin with
> letters -- mostly collection level extents of the form "ca. etc. etc."
> 
> But there aren't many.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/bentley-historical-library/vandura/pull/218#issuecomment-140869103
> .

## 

_Max Eckard_
_Assistant Archivist for Digital Curation_

Bentley Historical Library
1150 Beal Ave.
Ann Arbor, MI 48109-2113
734/763-7518 <734.763.7518>
http://bentley.umich.edu/

**Comment by walkerdb** [comment]
Turns the regex I was using to check extents was missing the tags that have attributes (like collection-level extents). Whoops. I'll go back and make the remaining edits.

**Comment by walkerdb** [comment]
#219 should be the last of them.

**Pull request merged**
