### PR TITLE
testing new cleanup script

### PR DESCRIPTION
**Pull request by djpillen**
Trying to put all my cleanup scripts into one comprehensive thing that I can easily run from time to time.

The majority of the changes here seem to be from a script that propagates authfilenumbers -- looks like it's mostly been added to things like "University of Michigan" and "Ann Arbor (Mich.)" that have subdivided terms. I don't think that should be a problem, though... right?

### CODE REVIEW

**Comment by walkerdb** [comment]
I think the original lcnaf reconciliation script skipped over anything with a "--" subdivision. This way might be fine? I don't know how ASpace propagates authority links when it splits a subject up. (like, would the "Sports" in "University of Michigan. Sports" be assigned the University of Michigan authority number?)

**Comment by djpillen** [comment]
In cases like:

University of Michigan. School of Music. [http://id.loc.gov/authorities/names/n82063886]
University of Michigan. Contemporary Directions Ensemble. [http://id.loc.gov/authorities/names/nr95015291]
etc.

Separate agent records are made with the correct authority id for each, since the subdivisions constitute separate parts of the agent itself.

In cases like:

University of Michigan--Faculty.
University of Michigan--Buildings.
University of Michigan--Maps.

Each of those corresponds to only one agent (University of Michigan) with one authority id (http://id.loc.gov/authorities/names/n79021846) with subdivided subject terms. The subdivided terms are applied at the point at which the agent is linked to from another record; they don't actually appear in the agent record itself. A given resource might have many "Agent Links" that all point to the same University of Michigan agent, and each of those agent links in the resource would have specific Terms/Subdivisions that are scoped only to that instance of the agent being linked.

I think that makes sense.

**Comment by walkerdb** [comment]
That sounds fine to me then. Think we're good to merge?

**Comment by djpillen** [comment]
Should be good to go.

**Pull request merged**
