### PR TITLE
Container "label" attribute cleanup

### PR DESCRIPTION
**Pull request by walkerdb**
Normalized label attribute values and ensured that they were only plural if they represented a range of objects.

### CODE REVIEW

**Comment by walkerdb** [comment]
Also it's worth noting that 95 container tags do not have any labels at all -- is that something we should try to fix?

**Comment by djpillen** [comment]
The most important thing is that each container has a type. I think the
label is another example of something that is used primarily for dlxs, and
is actually used differently in aspace (and I think differently than it's
intended EAD).

In Aspace the type attribute becomes the container type, and the label
isn't actually stored (at least not by the container plugin). Are there any
missing types?

**Comment by walkerdb** [comment]
Looks like 90 containers are missing types. Looking at the actual examples, the tags that pop up also account for most of the tags missing labels as well.

65 are in "houghton.xml", all being container tags with no attributes, each representing a "page", possibly of a map
22 are in "winchell.xml", all representing individual pages of a volume.

The rest are just obvious mistakes.

For the two main issues above, should we just add something like type="volume" and label="Page", or something of the sort?

**Comment by djpillen** [comment]
Ah, yeah, I think those are actually container tags in indexes/non
component elements. As such, those do not/should not make containers in
aspace and do not actually function like containers anywhere else. I think
I've modified the importer to handle those cases appropriately. It would be
worth verifying, but in cases in which container tags appear in non-<c0x>
tags, I don't think they really matter (at least not in the way that other
container tags do)

**Comment by eckardm** [comment]
I'm inclined to just ignore these, but if we did want to verify this, how
would we?

On Mon, Aug 3, 2015 at 2:51 PM, djpillen notifications@github.com wrote:

> Ah, yeah, I think those are actually container tags in indexes/non
> component elements. As such, those do not/should not make containers in
> aspace and do not actually function like containers anywhere else. I think
> I've modified the importer to handle those cases appropriately. It would be
> worth verifying, but in cases in which container tags appear in non-<c0x>
> tags, I don't think they really matter (at least not in the way that other
> container tags do)
> On Aug 3, 2015 2:25 PM, "Walker Boyle" notifications@github.com wrote:
> 
> > Looks like 90 containers are missing types. Looking at the actual
> > examples, the tags that pop up also account for most of the tags missing
> > labels as well.
> > 
> > 65 are in "houghton.xml", all being container tags with no attributes,
> > each representing a "page", possibly of a map
> > 22 are in "winchell.xml", all representing individual pages of a volume.
> > 
> > The rest are just obvious mistakes.
> > 
> > For the two main issues above, should we just add something like
> > type="volume" and label="Page", or something of the sort?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/bentley-historical-library/vandura/pull/140#issuecomment-127362094
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/bentley-historical-library/vandura/pull/140#issuecomment-127368908
> .

## 

_Max Eckard_
_Assistant Archivist for Digital Curation_

Bentley Historical Library
1150 Beal Ave.
Ann Arbor, MI 48109-2113
734/763-7518 <734.763.7518>
http://bentley.umich.edu/

**Comment by eckardm** [comment]
Dallas and I just talked. Yes, let's ignore. The BHL EAD Converter takes care of this.

**Pull request merged**
