### PR TITLE
removing duplicate bioghist tag

### PR DESCRIPTION
**Pull request by djpillen**

### CODE REVIEW

**Comment by eckardm** [comment]
I'm going to talk to Walker about trying to programmatically identify these unnecessarily nested elements.

**Comment by djpillen** [comment]
I've already checked (
https://github.com/djpillen/bentley_scripts/blob/master/find_nested_duplicates.py).
I don't think there are any more, but the problem with identifying these is
that most tags CAN be nested within each other, so sometimes it's
necessarily nested, and sometimes it's unnecessarily nested, and the only
way you can really tell is by looking at the context of each one. It also
doesn't help that most of the remaining nested tags are in indexes and
other elements of the "additional descriptive group" which are, by their
very nature, kind of weird. The other thing is that most nested tags are
harmless.

So, yeah, identifying nested elements programmatically is easy, but
identifying problematic ones could be...problematic. I'm not sure if it's
worth spending too much time trying to do programmatically, especially with
all of the other things to be done.

On Mon, Aug 31, 2015 at 9:12 AM, Max Eckard notifications@github.com
wrote:

> I'm going to talk to Walker about trying to programmatically identify
> these unnecessarily nested elements.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/bentley-historical-library/vandura/pull/200#issuecomment-136366974
> .

## 

_Dallas Pillen_Project Archivist

  Bentley Historical Library http://bentley.umich.edu/
  1150 Beal Avenue
  Ann Arbor, Michigan 48109-2113
  734.647.3559
  Twitter https://twitter.com/umichBentley Facebook
https://www.facebook.com/bentleyhistoricallibrary

**Comment by eckardm** [comment]
Good points. I asked Walker to do an initial exploration to at least
identify the unnecessarily (chose that word specifically since you're
right, none of these are technically invalid) nested ones (we were thinking
if an element has only 1 child and that child is the same exact thing) them
so that we can see how big the issue is and see how hard it is to figure
out which ones are problematic.

On Mon, Aug 31, 2015 at 9:39 AM, djpillen notifications@github.com wrote:

> I've already checked (
> 
> https://github.com/djpillen/bentley_scripts/blob/master/find_nested_duplicates.py
> ).
> I don't think there are any more, but the problem with identifying these is
> that most tags CAN be nested within each other, so sometimes it's
> necessarily nested, and sometimes it's unnecessarily nested, and the only
> way you can really tell is by looking at the context of each one. It also
> doesn't help that most of the remaining nested tags are in indexes and
> other elements of the "additional descriptive group" which are, by their
> very nature, kind of weird. The other thing is that most nested tags are
> harmless.
> 
> So, yeah, identifying nested elements programmatically is easy, but
> identifying problematic ones could be...problematic. I'm not sure if it's
> worth spending too much time trying to do programmatically, especially with
> all of the other things to be done.
> 
> On Mon, Aug 31, 2015 at 9:12 AM, Max Eckard notifications@github.com
> wrote:
> 
> > I'm going to talk to Walker about trying to programmatically identify
> > these unnecessarily nested elements.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/bentley-historical-library/vandura/pull/200#issuecomment-136366974
> > 
> > .
> 
> ## 
> 
> _Dallas Pillen_Project Archivist
> 
> Bentley Historical Library http://bentley.umich.edu/
> 1150 Beal Avenue
> Ann Arbor, Michigan 48109-2113
> 734.647.3559
> Twitter https://twitter.com/umichBentley Facebook
> https://www.facebook.com/bentleyhistoricallibrary
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/bentley-historical-library/vandura/pull/200#issuecomment-136374232
> .

## 

_Max Eckard_
_Assistant Archivist for Digital Curation_

Bentley Historical Library
1150 Beal Ave.
Ann Arbor, MI 48109-2113
734/763-7518 <734.763.7518>
http://bentley.umich.edu/

**Comment by walkerdb** [comment]
I ran the [script](https://github.com/walkerdb/bentley_code/blob/master/one-off%20scripts/check_tag_nesting/check_nested_tags.py), but it looks like Dallas has it covered! [Here are the results](https://docs.google.com/spreadsheets/d/15H5Wk7DukIjD4HB71yRHKN5TKMfi312p5oxlt2eUQYQ/edit#gid=0) -- all that came up were some `<controlaccess>`, `<descgroup>`, and `<relatedematerial>` tags, all of which I assume are fine.

**Comment by eckardm** [comment]
My only question is <relatedmaterial> since <controlaccess> and <descgroup>
are already in Dallas's script as okay. Are the <relatedmaterial> tags
good, Dallas?

On Mon, Aug 31, 2015 at 11:34 AM, Walker Boyle notifications@github.com
wrote:

> I ran the script
> https://github.com/walkerdb/bentley_code/blob/master/one-off%20scripts/check_tag_nesting/check_nested_tags.py,
> but it looks like Dallas has it covered! Here are the results
> https://docs.google.com/spreadsheets/d/15H5Wk7DukIjD4HB71yRHKN5TKMfi312p5oxlt2eUQYQ/edit#gid=0
> -- all that came up were some <controlaccess>, <descgroup>, and
> <relatedematerial> tags, all of which I assume are fine.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/bentley-historical-library/vandura/pull/200#issuecomment-136407718
> .

## 

_Max Eckard_
_Assistant Archivist for Digital Curation_

Bentley Historical Library
1150 Beal Ave.
Ann Arbor, MI 48109-2113
734/763-7518 <734.763.7518>
http://bentley.umich.edu/

**Comment by djpillen** [comment]
I think I manually checked those because there were only a couple. They
looked okay to me. It was essentially something like:

<relatedmaterial>
<head>Related Materials</head>
<relatedmaterial>There are some related materials in the Bentley's
collection</relatedmaterial>
<relatedmaterial>There are also some related materials at the state
archive</relatedmaterial>
</relatedmaterial>

Or something like that. I assume that those will just make separated
Related Material notes in ASpace, but it might be worth verifying that it
will import/export okay.

On Mon, Aug 31, 2015 at 11:41 AM, Max Eckard notifications@github.com
wrote:

> My only question is <relatedmaterial> since <controlaccess> and <descgroup>
> are already in Dallas's script as okay. Are the <relatedmaterial> tags
> good, Dallas?
> 
> On Mon, Aug 31, 2015 at 11:34 AM, Walker Boyle notifications@github.com
> wrote:
> 
> > I ran the script
> > <
> > https://github.com/walkerdb/bentley_code/blob/master/one-off%20scripts/check_tag_nesting/check_nested_tags.py
> > ,
> > but it looks like Dallas has it covered! Here are the results
> > <
> > https://docs.google.com/spreadsheets/d/15H5Wk7DukIjD4HB71yRHKN5TKMfi312p5oxlt2eUQYQ/edit#gid=0
> > 
> > -- all that came up were some <controlaccess>, <descgroup>, and
> > <relatedematerial> tags, all of which I assume are fine.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/bentley-historical-library/vandura/pull/200#issuecomment-136407718
> > 
> > .
> 
> ## 
> 
> _Max Eckard_
> _Assistant Archivist for Digital Curation_
> 
> Bentley Historical Library
> 1150 Beal Ave.
> Ann Arbor, MI 48109-2113
> 734/763-7518 <734.763.7518>
> http://bentley.umich.edu/
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/bentley-historical-library/vandura/pull/200#issuecomment-136410598
> .

## 

_Dallas Pillen_Project Archivist

  Bentley Historical Library http://bentley.umich.edu/
  1150 Beal Avenue
  Ann Arbor, Michigan 48109-2113
  734.647.3559
  Twitter https://twitter.com/umichBentley Facebook
https://www.facebook.com/bentleyhistoricallibrary

**Pull request merged**
