### PR TITLE
numbers that are dates and validation errors (also some certainty stuff)

### PR DESCRIPTION
**Pull request by eckardm**
OK, I finally had some time to look at numbers that might be dates.

I stripped the original CSV of non-dates and typos (since Devon fixed those). I tried to account for approximate certainty, as well as bulk dates and academic years as dates. Thanks, Dallas, for pointing those out. That being said, I tried accounting for all that stuff [fairly inelegantly](https://github.com/eckardm/work-stuff/blob/master/numbers_that_might_be_dates_fix.py), so some may have still slipped through the cracks. I cleaned a bit after running the script, but let me know if anything seems terribly off.

Along the way, I realized that some of our EADs don't validate. This was in part because of nested unitdates which were a result of the above inelegance. But I also realized that there were EADs that didn't validate for other reasons (like Genre Terms being empty, and dimension being singular instead of plural, and some others) so I fixed those as well.

### CODE REVIEW

**Comment by walkerdb** [comment]
Looks good!

**Comment by djpillen** [comment]
Just taking a quick look through this, I do actually see quite a few things that got tagged as unitdates that I think are not properly unitdates. Like the following:

 <unittitle>James Jones Family of Meade, Michigan, <unitdate normal="1804/1987" type="inclusive">1804-1987</unitdate>, booklet by H. G. Cope, updated <unitdate type="inclusive" normal="1987">1987</unitdate></unittitle>

 <unittitle>White, Albert E. (Director <unitdate normal="1920/1953" type="inclusive">1920-1953</unitdate>) <unitdate type="inclusive" normal="1948/1958">1948-1958</unitdate></unittitle>

  <unittitle>Botany at the University of Michigan through the First Century <unitdate normal="1837/1937" type="inclusive">circa 1837-1937</unitdate> manuscript, <unitdate type="inclusive" normal="1951" certainty="approximate">1951</unitdate></unittitle>

However, examples like that are mixed in throughout a lot of these EADs and would probably be difficult/not worth the time to isolate, and there are probably countless existing examples like that that we had nothing to do with, so it's probably not really a big deal.

Another thing that I notice in this pull request that might be worth quickly looking into are dates in parentheses. It looks like these are mostly bulk dates, things like (primarily 1990-1995). Really, those shouldn't be in parens, or the parens should be within the unitdate tags, not around -- I think DLXS adds parens around bulk dates (though maybe just at the series/collection levels?), and otherwise the type="bulk" attribute or the "primarly YYYY-YYYY" date expression should take care of that anyway, and if we don't remove those we're probably going to have some strange looking things coming back out of ASpace.

But really, it's probably more important to just say that we're done with dates soon than to keep looking for edge cases to nitpick (talking mostly to myself here).

**Comment by eckardm** [comment]
Yeah let's look into the parenthesis thing, especially if DLXS adds them.

On Fri, Oct 2, 2015 at 2:32 PM, djpillen notifications@github.com wrote:

> Just taking a quick look through this, I do actually see quite a few
> things that got tagged as unitdates that I think are not properly
> unitdates. Like the following:
> 
> <unittitle>James Jones Family of Meade, Michigan, <unitdate
> normal="1804/1987" type="inclusive">1804-1987</unitdate>, booklet by H. G.
> Cope, updated <unitdate type="inclusive"
> normal="1987">1987</unitdate></unittitle>
> 
> <unittitle>White, Albert E. (Director <unitdate normal="1920/1953"
> type="inclusive">1920-1953</unitdate>) <unitdate type="inclusive"
> normal="1948/1958">1948-1958</unitdate></unittitle>
> 
> <unittitle>Botany at the University of Michigan through the First Century
> <unitdate normal="1837/1937" type="inclusive">circa 1837-1937</unitdate>
> manuscript, <unitdate type="inclusive" normal="1951"
> certainty="approximate">1951</unitdate></unittitle>
> 
> However, examples like that are mixed in throughout a lot of these EADs
> and would probably be difficult/not worth the time to isolate, and there
> are probably countless existing examples like that that we had nothing to
> do with, so it's probably not really a big deal.
> 
> Another thing that I notice in this pull request that might be worth
> quickly looking into are dates in parentheses. It looks like these are
> mostly bulk dates, things like (primarily 1990-1995). Really, those
> shouldn't be in parens, or the parens should be within the unitdate tags,
> not around -- I think DLXS adds parens around bulk dates (though maybe just
> at the series/collection levels?), and otherwise the type="bulk" attribute
> or the "primarly YYYY-YYYY" date expression should take care of that
> anyway, and if we don't remove those we're probably going to have some
> strange looking things coming back out of ASpace.
> 
> But really, it's probably more important to just say that we're done with
> dates soon than to keep looking for edge cases to nitpick (talking mostly
> to myself here).
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/bentley-historical-library/vandura/pull/240#issuecomment-145117236
> .

## 

_Max Eckard_
_Assistant Archivist for Digital Curation_

Bentley Historical Library
1150 Beal Ave.
Ann Arbor, MI 48109-2113
734/763-7518 <734.763.7518>
http://bentley.umich.edu/

**Comment by djpillen** [comment]
:+1: 

Like, I'm not 100% sure that it adds them at every level (in fact I'm pretty sure that it only adds them at collection and series levels), but even if it doesn't, this seems like one of those things that should be handled by the display system, not by the way we enter data. As in, I don't think we would want our future guidelines to be:
- When entering inclusive dates, enter them like normal. When entering bulk dates, enclose the date expression in parentheses.

Really, the date type should be all that's needed. Plus, it's not as though "Correspondence, 1900-1950, bulk 1920-1930" makes less sense than "Correspondence, 1900-1950 (bulk 1920-1930)," but something like "Correspondence (), 1900-1950, bulk 1920-1930" or having those dates get caught up in the date moving/duplication script would be kinda weird. 

This should also be fairly easy to fix.

Okay I'm going to stop doing work things now :wave:

**Pull request merged**
