### PR TITLE
Move problematic unitdate tags outside of unittitles

### PR DESCRIPTION
**Pull request by walkerdb**
A bit of a hack-y fix to keep ASpace from mangling complicated unittitles into ungrammatical blocks. Original unitdate contents remain in unittitle.

Code for the fix can be found [here](https://github.com/walkerdb/bentley_code/blob/master/one-off%20scripts/unitdates_in_unittitles/unitdates_unittitles_fix.py).

### CODE REVIEW

**Comment by eckardm** [comment]
For posterity's sake, is this a subset of unitdates within unittitles or all unidates in unittitles? It looks like you are skipping over the ones where the two unitdates are right at the end...

**Comment by walkerdb** [comment]
Yeah -- it's a subset based on just a few criteria:
1. There is more than one unitdate in the title
2. At least one of the unitdate tags has a tail (non-tag textual content following its closing tag) that is greater than 5 characters long.

This catches most of the cases where just blindly moving dates to the end of the ASpace title would result in an incomprehensible sentence, without casting too wide of a net.

It would also be pretty easy to modify the script to run on a different set of criteria, if we ever wanted to try it on a wider set of items.

**Comment by eckardm** [comment]
Hey Walker,

Let's refine these conditions:
1. Keep this one.
2. This one should really just be ensuring that the last unitdate (not any of them) has a tail.

Then, we thought of another subset that needs to get addressed in a certain way:
1. In addition, if it meets the first two criteria, and one or more of the dates is at the end (separated by a comma, the word "and," and maybe a space), then keep those unitdates in the unittitles and strip out the text between them (the comma and the "and"--I think it would be OK if we kept the space). 

This is to account for these situations:

The "at the end" part...

<unittitle>Economic Symposium on the occasion of the Twentieth Anniversary of the Employment Act of <unitdate type="inclusive" normal="1946">1946</unitdate> Washington., <unitdate type="inclusive" normal="1966-02-23">February 23, 1966</unitdate></unittitle>

We can assume that if there are dates at the end that these are more likely to be the actual date.

The "one or more" part...

<unittitle>Correspondence, <unitdate>1900</unitdate>, <unitdate>1905</unitdate> and <unitdate>undated</unitdate></unittitle>

Sometimes there are more than one date at the end (maybe your tail of less than 5 technique could catch these).

Let me know if that makes sense! Of course, this only refines but does not perfect these changes. We'll probably take another close look after your next PR to see what else can be refined.

Devon also did a PR, so I'm going to accept that. I'm assuming you can just redo yours whenever you like.

Thanks!

**Comment by walkerdb** [comment]
Thanks! Yeah this is re-doable whenever.

I'm not sure if this came across (maybe it did) - but the criteria are treated as an "and", not an "or" -- so only unittitles with multiple unitdates as well as at least one tail > x characters for one of the tags are caught by the script.

re: the tail thing - I'm not sure I understand the reasoning for only counting the tail of the last date. For example, if we have this unittitle:

```
Economic Symposium on the occasion of the Twentieth Anniversary of the Employment Act of <unitdate>1946</unitdate> Washington., <unitdate>February 23, 1966</unitdate>
```

if we were only checking the tail of the last entry, it would not be caught by the script, and would be normalized by ASpace into something like

```
Economic Symposium on the occasion of the Twentieth Anniversary of the Employment Act of, Washington, 1946, February 23, 1966
```

Which doesn't seem right. I may just be misreading the comment.

For the second example - is the concern leftover commas or "and"s? When the unitdates are in a close sequence like that, I don't think any context is lost when ASpace strips them out.

**Comment by eckardm** [comment]
Yes, sorry for the confusion, I wasn't very clear on what we're after.

Here's what we're trying to account for... times when we can safely assume that one of the dates is not the actual date of creation. That time seems like when there are multiple dates in a unittitle, one or more of which appear in the middle and one or more of which appear at the end. It is likely that the ones in the middle (e.g., Employment Act of 1946) are not the actual date of creation while the ones at the end (February 23, 1966) are. 

When I said "keep the unitdates in the unittitles" what I meant was two things:
1. For the date that is not the actual date of creation (at least, the date we're assuming is not the date of creation because it is not at the end), leave the text but not the tags. 
2. For the date(s) at the end we are assuming are the date of creation (again, not always going to be perfect), leave the text and the tags (so ASpace does it's normal thing), generating a display string that should appear pretty correctly and parsing a unitdate. 

Essentially, we're trying to make sure that our example (which I've tweaked a little below to get a point accross) gets picked up and edited so that ASpace treats it properly. That is, so that...

```
Economic Symposium on the occasion of the Twentieth Anniversary of the Employment Act of <unitdate>1946</unitdate> Washington., <unitdate>February 23, 1966</unitdate>, and <unitdate>undated</unitdate>
```

...gets turned by your script into...

```
Economic Symposium on the occasion of the Twentieth Anniversary of the Employment Act of 1946 Washington., <unitdate>February 23, 1966</unitdate> <unitdate>undated</unitdate>
```

...and will appear in ASpace like this (commas automatically added)...

unittitle: Economic Symposium on the occasion of the Twentieth Anniversary of the Employment Act of 1946 Washington, February 23, 1966, undated

unitdate: February 23, 1966

unitdate: undated

I was having you strip out the word "and" and all that so that we don't end up with...

unittitle: Economic Symposium on the occasion of the Twentieth Anniversary of the Employment Act of 1946 Washington and, February 23, 1966, undated

Hopefully that's starting to make some sense! Feel free to ask more questions for clarification, especially sense I won't see you this week.

**Comment by walkerdb** [comment]
Ah, ok - thanks! That does make sense now.

I'll close this PR and take a look at these on Thursday.

Good luck at SAA!

**Comment by eckardm** [comment]
Awesome. And thanks!

On Tuesday, August 18, 2015, Walker Boyle notifications@github.com wrote:

> Ah, ok - thanks! That does make sense now.
> 
> I'll close this PR and take a look at these on Thursday.
> 
> Good luck at SAA!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/bentley-historical-library/vandura/pull/177#issuecomment-132403822
> .

## 

_Max Eckard_
_Assistant Archivist for Digital Curation_

Bentley Historical Library
1150 Beal Ave.
Ann Arbor, MI 48109-2113
734/763-7518 <734.763.7518>
http://bentley.umich.edu/

**Comment by walkerdb** [comment]
Hi! Hope the brown bag went well!

After looking though things and writing some additional code (things like trailing commas and "and"s are now cleaned in all unittitles with multiple ending unitdates - there are ~15,000 of these), I have a few further questions:

##### _on unittitles consisting only of unitdates:_

What should we do with these? For example:

```
1859, 1903-1904, 1906, 1908
```

Leaving it solely to ASpace's devices would result in a mess of commas, but if we were to move all the dates outside of the unittitle and clean the commas, the unittitle would end up completely empty. The keep-the-text-and-append-unitdates-outside-unittitle method would work, but ASpace would render it as `1859, 1903-1904, 1906, 1908, 1859, 1903-1904, 1906, 1908`, which doesn't seem ideal.

Maybe this is a candidate for a manual editing project to add more textual context to the unittitle? I can run a check to see how many of these there are.

##### _on removing only the last unitdate:_

Looking through the examples, it seems like there are enough cases that don't fit the last-unitdate-only model that it may be worth reconsidering that method. For example, there are often multiple legitimate date ranges:

```
Reunion minute book 1885-1891 volume also contains reunion register, 1860-1892
```

There are also cases like this:

```
Campaigns 1972-1975 (including 1974 Charter Revision)
```

where just going by the last unitdate would give us an inaccurate result.

It actually looks like cases along the lines of the "employment act of 1946" example given above, where the date is part of a noun, are in the minority.

With that in mind, I'm still leaning towards the original option -- this seems to be a case where we would rather be inclusive than exclusive, and I'm not sure how feasible it would be to write code that can discern the difference in grammatical function between arbitrary dates in a sentence. I also don't know what the benefits would be for choosing to be more restrictive here, but this is likely just a result of my not having a very clear idea of how the `<did>` unitdates are used in ASpace and (eventually) in the access system. Happy to talk further about this - maybe when you get back on Monday?

**Comment by walkerdb** [comment]
also, if you haven't seen this:

<blockquote class="twitter-tweet" lang="en"><p lang="en" dir="ltr">General feedback on ArchivesSpace-Archivematica integration project demo at <a href="https://twitter.com/hashtag/saa15?src=hash">#saa15</a> brown-bag session: &quot;Wheee!&quot;</p>&mdash; Kate Tasker (@kate_tasker) <a href="https://twitter.com/kate_tasker/status/634410246883123200">August 20, 2015</a></blockquote>

<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

:D

**Comment by walkerdb** [comment]
[solutions discussed in meeting]:

**Unittitles only made of unitdates:**
1. Remove and append all dates to after the unittitle; make new unittitle by pulling from parent's unittitle
2. Make a new unitdate by pulling the earliest and latest dates present, and calling it inclusive. Make original unittitle text-only.
3. Make all of unittitle text-only, pull and append unitdates after unittitle (this is the ""ugly in ASpace" version)

**re: script also pulling proper noun dates and calling them part of the date range:**
1. Check for outlier dates (comparing all dates in the unittitle), set aside those unittitles for manual review (this may pull out more examples than would be feasible to check)
2. Assume that the issue is not pervasive; go forward with original script
3. Possibly adopt the "create new unitdate based on earliest and latest unitdates of unittitle" solution above

Currently pending decision on which direction to choose.

**Comment by eckardm** [comment]
Update based on conversation with Mike...

Unittitles only made of unitdates: Not actually an issue with regard to this script or PR. However, I will try to replicate the display string issue when entering multiple dates from scratch and possibly report a bug.

Proper noun dates and date range dates: Go with number 1. We'll start with a range of 20 years and go from there.

**Pull request closed without merging**
