### PR TITLE
7/16 morning corrections

### PR DESCRIPTION
**Pull request by devonproudfoot**

### CODE REVIEW

**Comment by eckardm** [comment]
hmm, i think there is some debate as to whether it should be e e cummings or E. E. Cummings, what do you all think?

**Comment by djpillen** [comment]
LOC says E. E. Cummings with e e cummings as a variant form:

http://lccn.loc.gov/n79038464

Also, according to the indisputable Wikipedia, "Cummings himself used both the lowercase and capitalized versions, though he most often signed his name with capitals."

**Comment by devonproudfoot** [comment]
I agree with Dallas, I went with what the LOC had, but I don't think it is that big of a deal either way.  Let me know, I can change it back if need be.

**Comment by eckardm** [comment]
Who is LOC again?

On Thu, Jul 16, 2015 at 1:59 PM, Devon Proudfoot notifications@github.com
wrote:

> I agree with Dallas, I went with what the LOC had, but I don't think it is
> that big of a deal either way. Let me know, I can change it back if need be.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/bentley-historical-library/vandura/pull/93#issuecomment-122036136
> .

## 

_Max Eckard_
_Assistant Archivist for Digital Curation_

Bentley Historical Library
1150 Beal Ave.
Ann Arbor, MI 48109-2113
734/763-7518 <734.763.7518>
http://bentley.umich.edu/

**Comment by djpillen** [comment]
Sorry, I meant loc

**Pull request merged**
