### PR TITLE
add uuids to c0x elements

### PR DESCRIPTION
**Pull request by walkerdb**
meant to possibly enable linking removable media items in the project document (based off of the EAD data) to their eventual ASpace homes.

### CODE REVIEW

**Comment by djpillen** [comment]
I just talked to Greg and there are a bunch of EAD updates pending right now that should make it into the S: drive by the end of this week, so we can do an update early next week.

Would it be okay if we waited until all of the pending changes were incorporated before adding uuids? We can incorporate S drive modifications early next week and then quickly add uuids before copying over our current vandura copies to the S drive master folder.

Though I do still worry that, in the next couple months, some changes will be made to finding aids that will result in the macros being entirely rerun, leading to a loss of these uuids. My guess is that that will likely not really matter (if new uuids can be assigned and the project document updated)... is that right?

**Comment by walkerdb** [comment]
Sure, that's fine - they're really easy to add. And there will be backup info in the sheet as well (probably the original unittitle trail idea).

I'll close the PR for now.

**Comment by eckardm** [comment]
That seems right to me... at least the "new UUIDs can be assigned" part.
Question: if a macro gets reran, that would mean that the UUID gets
replaced, and then it woudn't match on Walker's tracking sheet, but we'd
have the breadcrumb trail as a backup, right?

On Wed, Feb 3, 2016 at 10:44 AM, djpillen notifications@github.com wrote:

> I just talked to Greg and there are a bunch of EAD updates pending right
> now that should make it into the S: drive by the end of this week, so we
> can do an update early next week.
> 
> Would it be okay if we waited until all of the pending changes were
> incorporated before adding uuids? We can incorporate S drive modifications
> early next week and then quickly add uuids before copying over our current
> vandura copies to the S drive master folder.
> 
> Though I do still worry that, in the next couple months, some changes will
> be made to finding aids that will result in the macros being entirely
> rerun, leading to a loss of these uuids. My guess is that that will likely
> not really matter (if new uuids can be assigned and the project document
> updated)... is that right?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/bentley-historical-library/vandura/pull/350#issuecomment-179301156
> .

## 

_Max Eckard_
_Assistant Archivist for Digital Curation_

Bentley Historical Library
1150 Beal Ave.
Ann Arbor, MI 48109-2113
734/763-7518 <734.763.7518>
http://bentley.umich.edu/

**Comment by djpillen** [comment]
Yeah that's right. But theoretically we could add new uuids to that EAD and
update the tracking sheet, right? Maybe? At least up until a certain point
(whenever we start tracking info on that document beyond the information
that's currently in the EAD)

On Wed, Feb 3, 2016 at 10:57 AM, Max Eckard notifications@github.com
wrote:

> That seems right to me... at least the "new UUIDs can be assigned" part.
> Question: if a macro gets reran, that would mean that the UUID gets
> replaced, and then it woudn't match on Walker's tracking sheet, but we'd
> have the breadcrumb trail as a backup, right?
> 
> On Wed, Feb 3, 2016 at 10:44 AM, djpillen notifications@github.com
> wrote:
> 
> > I just talked to Greg and there are a bunch of EAD updates pending right
> > now that should make it into the S: drive by the end of this week, so we
> > can do an update early next week.
> > 
> > Would it be okay if we waited until all of the pending changes were
> > incorporated before adding uuids? We can incorporate S drive
> > modifications
> > early next week and then quickly add uuids before copying over our
> > current
> > vandura copies to the S drive master folder.
> > 
> > Though I do still worry that, in the next couple months, some changes
> > will
> > be made to finding aids that will result in the macros being entirely
> > rerun, leading to a loss of these uuids. My guess is that that will
> > likely
> > not really matter (if new uuids can be assigned and the project document
> > updated)... is that right?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/bentley-historical-library/vandura/pull/350#issuecomment-179301156
> > 
> > .
> 
> ## 
> 
> _Max Eckard_
> _Assistant Archivist for Digital Curation_
> 
> Bentley Historical Library
> 1150 Beal Ave.
> Ann Arbor, MI 48109-2113
> 734/763-7518 <734.763.7518>
> http://bentley.umich.edu/
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/bentley-historical-library/vandura/pull/350#issuecomment-179309449
> .

## 

_Dallas Pillen_Assistant Archivist for Metadata and Digital Projects

  Bentley Historical Library http://bentley.umich.edu/
  1150 Beal Avenue
  Ann Arbor, Michigan 48109-2113
  734.647.3559
  Twitter https://twitter.com/umichBentley Facebook
https://www.facebook.com/bentleyhistoricallibrary

**Comment by djpillen** [comment]
Even then we could use the breadcrumb to update the uuid in the document if
necessary.

On Wed, Feb 3, 2016 at 10:59 AM, Dallas Pillen djpillen@umich.edu wrote:

> Yeah that's right. But theoretically we could add new uuids to that EAD
> and update the tracking sheet, right? Maybe? At least up until a certain
> point (whenever we start tracking info on that document beyond the
> information that's currently in the EAD)
> 
> On Wed, Feb 3, 2016 at 10:57 AM, Max Eckard notifications@github.com
> wrote:
> 
> > That seems right to me... at least the "new UUIDs can be assigned" part.
> > Question: if a macro gets reran, that would mean that the UUID gets
> > replaced, and then it woudn't match on Walker's tracking sheet, but we'd
> > have the breadcrumb trail as a backup, right?
> > 
> > On Wed, Feb 3, 2016 at 10:44 AM, djpillen notifications@github.com
> > wrote:
> > 
> > > I just talked to Greg and there are a bunch of EAD updates pending right
> > > now that should make it into the S: drive by the end of this week, so we
> > > can do an update early next week.
> > > 
> > > Would it be okay if we waited until all of the pending changes were
> > > incorporated before adding uuids? We can incorporate S drive
> > > modifications
> > > early next week and then quickly add uuids before copying over our
> > > current
> > > vandura copies to the S drive master folder.
> > > 
> > > Though I do still worry that, in the next couple months, some changes
> > > will
> > > be made to finding aids that will result in the macros being entirely
> > > rerun, leading to a loss of these uuids. My guess is that that will
> > > likely
> > > not really matter (if new uuids can be assigned and the project document
> > > updated)... is that right?
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > > https://github.com/bentley-historical-library/vandura/pull/350#issuecomment-179301156
> > > 
> > > .
> > 
> > ## 
> > 
> > _Max Eckard_
> > _Assistant Archivist for Digital Curation_
> > 
> > Bentley Historical Library
> > 1150 Beal Ave.
> > Ann Arbor, MI 48109-2113
> > 734/763-7518 <734.763.7518>
> > http://bentley.umich.edu/
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/bentley-historical-library/vandura/pull/350#issuecomment-179309449
> > .
> 
> ## 
> 
> _Dallas Pillen_Assistant Archivist for Metadata and Digital Projects
> 
>   Bentley Historical Library http://bentley.umich.edu/
>   1150 Beal Avenue
>   Ann Arbor, Michigan 48109-2113
>   734.647.3559
>   Twitter https://twitter.com/umichBentley Facebook
> https://www.facebook.com/bentleyhistoricallibrary

## 

_Dallas Pillen_Assistant Archivist for Metadata and Digital Projects

  Bentley Historical Library http://bentley.umich.edu/
  1150 Beal Avenue
  Ann Arbor, Michigan 48109-2113
  734.647.3559
  Twitter https://twitter.com/umichBentley Facebook
https://www.facebook.com/bentleyhistoricallibrary

**Comment by walkerdb** [comment]
Yeah we could just re-add new uuids then re-run the document-creation script again. At least, assuming it ends up being an automated thing.

**Pull request closed without merging**
