### PR TITLE
Add LC auth ids for matching geognames

### PR DESCRIPTION
**Pull request by walkerdb**
I've added geogname auth links to their respective LC resources

### CODE REVIEW

**Comment by eckardm** [comment]
Looks good, but can you change authfilenumber to id?

**Comment by eckardm** [comment]
Wait, nevermind.

**Comment by walkerdb** [comment]
This is only somewhat related, but it looks like there's an ongoing issue with newlines at the end of the EADs that gums up the diff viewer. I'm not sure what's going on -- there should have been newlines at the end of every file after the subject-heading normalization update, since the lxml prettyprint puts them there, and I went through every ead in Real_Masters folder. But they've all gone missing somehow in the meantime.

It's not a huge deal, but it does muddy the commit a bit. Any ideas on where the issue could be coming from?

**Comment by djpillen** [comment]
Maybe something in here can help?

https://help.github.com/articles/dealing-with-line-endings/

**Comment by walkerdb** [comment]
It actually looks like it was this commit:

https://github.com/bentley-historical-library/vandura/pull/29/files

Was that intended, or just a side-effect? I've been assuming we want to go with the extra line (stackoverflow suggests it's [standard for text-based files](http://stackoverflow.com/questions/729692/why-should-files-end-with-a-newline)), but if we actually don't want them I'll try to keep them out of the eads.

**Comment by djpillen** [comment]
Ah, yeah, that was unintentional...using an old script that rewrote EADs without pretty printing. Where is the script that you use to pretty print? I'll just try to incorporate that into any mass rewriting I do in the future.

**Comment by eckardm** [comment]
Do we want to try "git config --global core.autocrlf true"?

**Comment by eckardm** [comment]
I do get a warning about this whenever I do a push (or PR, can't remember when it happens).

**Comment by walkerdb** [comment]
The pretty-print code is [here](https://github.com/walkerdb/bentley_code/blob/master/one-off%20scripts/prettifydirectory.py). I set it up to use a module called [tqdm](https://github.com/noamraph/tqdm), which shows a handy progress bar in the command-line as it's processing, but if you don't want to deal with the dependency you should be able to just delete the import and remove the tqdm call in line 10.

**Comment by djpillen** [comment]
Awesome, thanks. I'll add that to my scripts that rewrite entire xml trees. Do you think we should run this against all of the EADs again so that we can have everything back to a baseline pretty printed version? 

Maybe we should also try git config --global core.autocrlf true just to be safe. I've never gotten a warning about this when doing a push or PR.

**Comment by walkerdb** [comment]
I pretty-printed everything in this last commit, so I think we should be set on that end.

**Comment by eckardm** [comment]
OK, so let's all try "git config --global core.autocrlf true"

**Pull request merged**
