### PR TITLE
Testing Walker's prettify scripts

### PR DESCRIPTION
**Pull request by djpillen**
I ran remove_newlines and prettifydirectory on everything. It seems to have gone okay, other than some lists got their formatting a little screwed up. But it doesn't look like it's screwed up in a way that will actually really matter, since I think we're pretty much done looking at lists, right?

### CODE REVIEW

**Comment by walkerdb** [comment]
The remove_newlines script is probably the list -destroying culprit, which should be fine since it is only meant to run on fresh-from-the-macro eads. I ran the prettify script just a few days ago and I don't believe it did anything to the lists.

One thing to note - the prettify script will crash on any ead with a collapsed list (when it runs into a problem it skips that ead and prints out an error message before continuing on).

**Comment by djpillen** [comment]
I got a little overeager and ran remove_newlines on everything because I didn't fully understand what it was going to do. Oops!

The prettify script didn't print out any errors for me, so I don't think anything got messed up. Do we still need lists to be formatted in a more readable way? It's not like DLXS or ASpace cares, but we might if we still have the need to look at any of them.

**Comment by walkerdb** [comment]
Probably not! I could remove the list formatting bits from the script if that would make things easier.

**Comment by djpillen** [comment]
It probably doesn't matter one way or the other.

**Comment by walkerdb** [comment]
The only real difference is the script would probably be a little more robust without the extra list code. Also at the moment if a new EAD has a mungled list you'd need to manually format it correctly before the rest of it can be prettified.

Either way works for me.

**Comment by djpillen** [comment]
Ah, yeah, if lists would need to be formatted manually then it would probably be best to remove it.

**Comment by walkerdb** [comment]
ok, will do.

**Comment by djpillen** [comment]
Okay. Well, I'll go ahead and accept this PR since it doesn't look like anything got messed up/will get messed up in the future. Thanks for the additional info on the newline and prettify scripts.

**Pull request merged**
